openapi: 3.0.0
info:
  title: 'LARAVEL Rest API DOCUMENTATION'
  description: 'L5 Swagger OpenApi description'
  contact:
    email: learn_poems@example.com
  license:
    name: 'Apache 2.0'
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
paths:
  /:
    get:
      description: 'Home page'
      responses:
        default:
          description: 'Welcome page'
  /api/poets:
    get:
      tags:
        - poets
      summary: 'Get all poets'
      description: 'Getting all poets with pagination.'
      operationId: getPoets
      parameters:
        -
          name: per_page
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          description: 'successful operation'
  /user:
    post:
      tags:
        - user
      summary: 'Create user'
      description: 'This can only be done by the logged in user.'
      operationId: createUser
      requestBody:
        description: 'Create user object'
        required: true
      responses:
        default:
          description: 'successful operation'
